services:
  - type: web
    name: varun-portfolio
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn portfolio_project.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: varun-portfolio-db
          property: connectionString

databases:
  - name: varun-portfolio-db
    databaseName: varun_portfolio
    user: varun_portfolio
