services:
  - type: web
    name: varun-portfolio
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn portfolio_project.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: True
      - key: SECRET_KEY
        generateValue: true
