# Generated by Django 5.0.6 on 2026-06-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issuer', models.CharField(max_length=100)),
                ('issue_date', models.DateField()),
                ('credential_id', models.CharField(blank=True, max_length=100)),
                ('credential_url', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='certifications/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-issue_date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('experience_type', models.CharField(choices=[('work', 'Work Experience'), ('internship', 'Internship'), ('research', 'Research'), ('volunteer', 'Volunteer')], default='work', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank if current', null=True)),
                ('description', models.TextField()),
                ('achievements', models.TextField(blank=True, help_text='One achievement per line')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('short_description', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('technologies', models.CharField(help_text='Comma-separated technologies', max_length=300)),
                ('github_url', models.URLField(blank=True)),
                ('live_demo_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('ongoing', 'Ongoing'), ('archived', 'Archived')], default='completed', max_length=20)),
                ('featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('accuracy', models.CharField(blank=True, help_text='e.g., 91.5% accuracy', max_length=100)),
                ('metric_1_label', models.CharField(blank=True, max_length=50)),
                ('metric_1_value', models.CharField(blank=True, max_length=50)),
                ('metric_2_label', models.CharField(blank=True, max_length=50)),
                ('metric_2_value', models.CharField(blank=True, max_length=50)),
                ('date_completed', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-featured', 'order', '-date_completed'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('authors', models.CharField(max_length=300)),
                ('conference', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('doi', models.CharField(blank=True, max_length=100)),
                ('paper_url', models.URLField(blank=True)),
                ('abstract', models.TextField()),
                ('keywords', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='publications/')),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default="Hi, I'm Varun", max_length=200)),
                ('hero_subtitle', models.TextField(default='AI researcher, IEEE published developer, and someone who builds things that actually work.')),
                ('hero_cta_text', models.CharField(default='View My Work', max_length=50)),
                ('hero_video_url', models.URLField(blank=True)),
                ('about_title', models.CharField(default='About Me', max_length=200)),
                ('about_description', models.TextField()),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('email', models.EmailField(default='varunnatesh10@gmail.com', max_length=254)),
                ('phone', models.CharField(default='9740791782', max_length=20)),
                ('location', models.CharField(default='Mysuru, Karnataka', max_length=100)),
                ('linkedin_url', models.URLField(default='https://linkedin.com/in/varun-k-n-566135251')),
                ('github_url', models.URLField(default='https://github.com/varunnatesh')),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resume/')),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('meta_keywords', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('programming', 'Programming Languages'), ('ml', 'Machine Learning'), ('dl', 'Deep Learning & CV'), ('data', 'Data Processing'), ('tools', 'Tools & Platforms')], max_length=20)),
                ('proficiency', models.IntegerField(default=80, help_text='Proficiency level (0-100)')),
                ('icon', models.CharField(blank=True, help_text='Icon class name', max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'order', 'name'],
            },
        ),
    ]
