# Generated by Django 5.0.6 on 2026-06-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_video_file',
            field=models.FileField(blank=True, help_text='Or upload video file directly (MP4 recommended)', null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='hero_video_url',
            field=models.URLField(blank=True, help_text='External video URL (YouTube, Vimeo, etc.)'),
        ),
    ]
