# Generated by Django 5.0.6 on 2026-06-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_siteconfiguration_hero_video_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='about_description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
